# Generated by Django 3.2.19 on 2023-06-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_doc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personne',
            old_name='mot_de_passe',
            new_name='adresse',
        ),
        migrations.AddField(
            model_name='personne',
            name='password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personne',
            name='tele',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
