# Generated by Django 3.2.19 on 2023-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_doc', '0002_auto_20230612_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='my_checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
